### ISSUE TITLE
Destination Window

### ISSUE THREAD

**Issue by raguramvv** [DCAN-Labs/file-mapper#1]
https://github.com/DCAN-Labs/file-mapper/tree/aa21eb5dce3867ea939261fc872501e79481182f

File Mapper Gui was functional at this commit.

Create new window in the GUI that gets the user to provide a destination argument for making either an absolute path or relative path to the desired destination.

**Comment by hough129** [comment]
Hi @raguramvv - we do not plan on supporting the file-mapper GUI moving forward, unfortunately! I am going to close this issue as not planned.
