### ISSUE TITLE
Put parcellations files in jsons and take out of the wrapper.

### ISSUE THREAD

**Issue by kathy-snider** [DCAN-Labs/file-mapper#4]
We used to do some kind of processing to the parcellations files, but now it is just renaming them. They could be in the json like any other pipeline files since they have predictable names. This would simplify the wrapper (ultimate goal: get rid of need for wrapper - see more issues).

**Comment by lundq163** [comment]
hi @kathy-snider, would you be able to clarify which parcellation files you are referring to and which json in the examples folder this issue is regarding?
