### ISSUE TITLE
Handle kwargs in BIDS

### ISSUE THREAD

**Issue by kathy-snider** [DCAN-Labs/file-mapper#6]
Allow a user to pass in a dictionary with key:value pairs. When reading the json, each filename string should be processed with the kwargs such that anything in the string that has {key} will be replaced with the corresponding value. 
This would allow us to pass in things like a subject, session, pipeline name, etc. for making derivatives and would move us closer to the ultimate goal: no need for a wrapper. (See other issues.)

**Comment by hough129** [comment]
Closing this, because I believe it was solved with the template feature.
